#!/usr/bin/env ruby

# This is a simple test runner for Rails projects, it requires no configuration.
# It will check the app, lib, and spec and or test directories for changes in .rb files.

require "bundler/inline"
require "csv"

gemfile do
  source "https://rubygems.org"

  gem "listen", require: true
end

def rspec?
  @rspec ||= Pathname.new(".").children.map(&:to_s).include? "spec"
end

SPRING_ENABLED = $ARGV.include?("--spring")
ONLY_FAILURES = $ARGV.include?("--only-failures")
FOCUSSED_TEST = $ARGV.find { |arg| arg.match?("_spec.rb") || arg.match?("_test.rb") }
command = rspec? ? "rspec -f doc #{"--only-failures" if ONLY_FAILURES}" : "rake test"
BASE_COMMAND = "bundle exec #{"spring " if SPRING_ENABLED}#{command}"
ONLY_FILE_COVERAGE = $ARGV.include?("--only-file-coverage")

trap "SIGINT" do
  puts "Exiting..."
  exit 0
end

def run_spec(test_file)
  test_file = rspec? ? test_file : "TEST=#{test_file}"
  command = "#{BASE_COMMAND} #{test_file}"
  puts "Running #{command} ..."
  Kernel.system(command)
  result = $CHILD_STATUS
  errors = (result == 0) || "Failed to run: #{test_file}"
  [result, nil, errors]
end

def potential_spec_or_test_files(path)
  test_file_string = path.to_s
  test_file_string = test_file_string.sub(/\A.\//, "")

  spec_or_test = rspec? ? "spec" : "test"
  base_test_dir = "./#{spec_or_test}"


  if test_file_string.end_with?("_#{spec_or_test}.rb") && test_file_string.start_with?("#{spec_or_test}/")
    [path]
  elsif test_file_string.start_with?("app/controllers")
    [
      File.join(base_test_dir, "requests", path.relative_path_from("app/controllers")).sub("_controller.rb", "_#{spec_or_test}.rb"), # request specs
      File.join(base_test_dir, "system", path.relative_path_from("app/controllers")).sub("_controller.rb", "_#{spec_or_test}.rb"), # request specs
      File.join(base_test_dir, path.relative_path_from("app/")).sub(".rb", "_#{spec_or_test}.rb"),
      File.join(base_test_dir, "requests", path.relative_path_from("app/controllers")).sub("_controller.rb", "/")
    ]
  elsif test_file_string.start_with?("app/")
    [
      File.join(base_test_dir, path.relative_path_from("app/")).sub(".rb", "_#{spec_or_test}.rb"),
      File.join(base_test_dir, path.relative_path_from("app/")).sub(".rb", "/")
    ]
  elsif test_file_string.start_with?("lib/")
    [File.join(base_test_dir, path).sub(".rb", "_#{spec_or_test}.rb")]
  else
    []
  end
end

def spec_or_test_file(path)
  return FOCUSSED_TEST if FOCUSSED_TEST

  potential_test_files = potential_spec_or_test_files(path)

  if potential_test_files.any?
    test_file = potential_test_files.find { File.exist?(it) || Dir.exist?(it) }

    if test_file.nil?
      puts "No test file found for #{path}, tried:"
      potential_test_files.map { puts " - #{it}" }
    end

    test_file
  else
    puts "No test file found for #{path}. Could not decide on a test location based on heuristics."
  end
end

code_dirs = %w[./app ./lib]
watch_dirs = []
watch_dirs += code_dirs
watch_dirs << "./spec" if rspec?
watch_dirs << "./test" if !rspec?

if ONLY_FILE_COVERAGE
  files = code_dirs.flat_map { Dir.glob("#{it}/**/*.rb") }

  results = files.map do |file|
    path = Pathname.new(file)
    test_file = spec_or_test_file(path)
    file_size = File.size(path)
    insignificant = file_size < 400
    potential_test_files = potential_spec_or_test_files(path) if test_file.nil?
    category = path.to_s.split("/")[0..2].select{ it != "." && !it.end_with?(".rb")}.join("/")
    {file:, category: ,test_file:, file_size:, insignificant:, potential_test_files:, ok: !!test_file}
  end
  puts "\n-----"

  puts "Considered #{files.count} that could use a spec."

  puts "No matching spec found for #{results.select { it[:test_file].nil? }.count} (considered #{results.count} files)"
  in_need_of_tests = results.select { it[:test_file].nil? && it[:insignificant] == false }
  puts "Of those without a spec, #{results.select { it[:test_file].nil? && it[:insignificant] == true }.count} were found to be insignificant, very small files, mostly light weight wrappers, leaving #{in_need_of_tests.count} to get more attention."
  puts ""
  puts "Most worriesome were these, reverse sorted by file size:"
  in_need_of_tests.sort_by { -it[:file_size] }[0...50].each do |file|
    puts "* #{file[:file]} (#{file[:file_size]})"
  end

  header = [results.first.keys.to_csv]
  File.write("spec_mapping.csv", (header + results.map { it.values.to_csv }).join(""))

  exit
end

queue = Queue.new

listener = Listen.to(*watch_dirs, relative: true, only: /.rb$/) do |modified, added, _removed|
  next unless modified.any? || added.any?

  files = modified + added
  files.map { |path_name| Pathname.new(path_name) }.each do |path|
    if (test_file = spec_or_test_file(path))
      queue << test_file

    end
  end
end

puts "Started listening..."
puts "  Commands are run using spring" if SPRING_ENABLED
puts "  Focussing only on #{FOCUSSED_TEST}" if FOCUSSED_TEST

# directly run a focussed test
queue << FOCUSSED_TEST if FOCUSSED_TEST

background_fiber = Fiber.new do
  listener.start

  loop do
    sleep(0.5)
    next if queue.empty?

    test_file = queue.pop
    run_spec(test_file) if test_file
  end
end

background_fiber.resume
